#!/usr/bin/env bash
# SPDX-FileCopyrightText: 2023 Robin Vobruba <hoijui.quaero@gmail.com>
# SPDX-License-Identifier: CERN-OHL-S-2.0

# Dependencies:
# apt-get install libreoffice

script_path="$(readlink -f "${BASH_SOURCE[0]}")"
script_dir="$(dirname "$script_path")"
script_name="$(basename "$script_path")"

function print_help() {

	echo -e "$script_name -"
	echo -e "Converts an ODP (Open Document Presentation"
	echo -e "=> LibreOffice/OpenOffice Presentation (MS PowerPoint alternative))"
	echo -e "to a PDF (Portable Document Format) file."
	echo -e ""
	echo -e "Usage:"
	echo -e "\t$script_name [OPTION...]"
	echo -e "Options:"
	echo -e "\t-h, --help"
	echo -e "\t\tPrint this usage help and exits"
	echo -e ""
}

# Process command line arguments
POSITIONAL=()
while [[ $# -gt 0 ]]
do
	arg="$1"
	shift # $2 -> $1, $3 -> $2, ...

	case "$arg" in
		-h|--help)
			print_help
			exit 0
			;;
		*) # non-/unknown option
			POSITIONAL+=("$arg") # save it in an array for later
			;;
	esac
done
set -- "${POSITIONAL[@]}" # restore positional parameters

in_odp="${1:-}"
out_pdf="${2:-}"

if [ -z "$in_odp" ]
then
	>&2 echo "ERROR: Please supply the ODP input file to convert to a PDF file."
	exit 1
fi

if [ -z "$out_pdf" ]
then
	out_pdf="${in_odp%.*}.pdf"
fi

mkdir -p "$(dirname "$out_pdf")"

echo "Generating '$out_pdf' (from '$in_odp') ..."
unoconv \
	--format pdf \
	--output "$out_pdf" \
	"$in_odp"
